import { type Tour, type TourOptions } from '../tour.ts';
import {
  type StepOptionsAttachTo,
  type Step,
  type StepOptions,
  type UnresolvedElement,
  type ResolvedElement,
  type ResolvedAttachTo
} from '../step.ts';
import { isFunction, isHTMLElement, isString } from './type-check.ts';

export class StepNoOp {
  constructor(_options: StepOptions) {}
}

export class TourNoOp {
  constructor(_tour: Tour, _options: TourOptions) {}
}

/**
 * Ensure class prefix ends in `-`
 * @param prefix - The prefix to prepend to the class names generated by nano-css
 * @return The prefix ending in `-`
 */
export function normalizePrefix(prefix?: string) {
  if (!isString(prefix) || prefix === '') {
    return '';
  }

  return prefix.charAt(prefix.length - 1) !== '-' ? `${prefix}-` : prefix;
}

function tryQuerySelector(query: string): HTMLElement | undefined {
  const element = document.querySelector<HTMLElement>(query);

  if(!element){
    console.error( `The element for this Shepherd step was not found ${query}` );
    return undefined;
  }

  return element;

}


function parseElement(step: Step, element: UnresolvedElement): ResolvedElement {

  if(!element){
    console.error( `The element for this Shepherd step was not found ${element}`);
    return undefined;
  }

  if(isHTMLElement(element)) {
    return element;
  }

  if(isString(element)){
    return tryQuerySelector(element);
  }

  const fnResult = element.call(step);
  if(!fnResult){
    return undefined;
  }

  if(isString(fnResult)){
    return tryQuerySelector(fnResult);
  }

  return fnResult;


}


export function parseAttachTo(step: Step): ResolvedAttachTo {
  const options = step.options.attachTo || {};

  const target = parseElement(step, options.element);
  const highlights = (options.highlightElements
    ?.map(el => parseElement(step, el))
    .filter(el => !!el)
  );

  const returnOpts: ResolvedAttachTo = {
    element: target,
    highlightElements: highlights,
    on: options.on
  }

  return returnOpts;
}

/**
 * Checks if the step should be centered or not. Does not trigger attachTo.element evaluation, making it a pure
 * alternative for the deprecated step.isCentered() method.
 */
export function shouldCenterStep(resolvedAttachToOptions: StepOptionsAttachTo) {
  if (
    resolvedAttachToOptions === undefined ||
    resolvedAttachToOptions === null
  ) {
    return true;
  }

  return !resolvedAttachToOptions.element || !resolvedAttachToOptions.on;
}

/**
 * Create a unique id for steps, tours, modals, etc
 */
export function uuid() {
  let d = Date.now();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (d + Math.random() * 16) % 16 | 0;
    d = Math.floor(d / 16);
    return (c == 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}
